INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (1, 'test_workflow1', 'template1', 1, true);
INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (2, 'test_workflow2', 'template2', 1, false);
INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (3, 'test_workflow3', 'template3', 1, true);
INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (4, 'test_workflow3', 'template1', 2, true);
INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (5, 'test_workflow4', 'template1', 2, true);
INSERT INTO workflows (workflow_id, workflow_name, template, user_id, active) VALUES (6, 'test_workflow4', 'template1', 2, true);
INSERT INTO workflow_steps(step_id, workflow_id, step_identifier, tool) VALUES (1, 4, 's1', 'One');
INSERT INTO workflow_steps(step_id, workflow_id, step_identifier, tool) VALUES (2, 4, 's2', 'Two');
INSERT INTO step_dependencies(dependent_step, prerequisite_step) VALUES (1, 2);
INSERT INTO workflow_global_params(workflow_global_id, workflow_id, parameter_name) VALUES (1, 4, 'globalOne');
INSERT INTO workflow_global_params(workflow_global_id, workflow_id, parameter_name) VALUES (2, 4, 'globalTwo');
INSERT INTO workflow_global_values(workflow_global_id, parameter_value) VALUES (2, 'value1');
INSERT INTO workflow_global_values(workflow_global_id, parameter_value) VALUES (2, 'value2');
INSERT INTO workflow_step_params(workflow_step_param_id, step_id, parameter_name) VALUES (1, 1, 'input_one');
INSERT INTO workflow_step_params(workflow_step_param_id, step_id, parameter_name) VALUES (2, 1, 'input_no_type');
INSERT INTO workflow_step_values(workflow_step_param_id, parameter_value) VALUES (1, '{$s2.out}');