package com.compomics.pladipus.model.db;

/**
 * Database table names
 */
public enum DbTable {
	USERS,
	USER_ROLES,
	ROLES,
	WORKFLOWS,
	COMMON_DEFAULTS,
	WORKFLOW_STEPS,
	WORKFLOW_GLOBAL_PARAMS,
	WORKFLOW_STEP_PARAMS,
	STEP_DEPENDENCIES,
	WORKFLOW_GLOBAL_VALUES,
	WORKFLOW_STEP_VALUES
}